### ISSUE TITLE
[Logo Request] A logo for HITSZ-OpenAuto

### ISSUE THREAD

**Issue by kowyo** [PetricaT/ProgrammingVTuberLogos-Addon#1]
Hi! Thank you for making this project. I read your README and wonder if you could make a logo for a project of our school. That is  because [our team doen't have someone who is good at logo design](https://github.com/HITSZ-OpenAuto/hoa.moe/issues/69).

Our project is a platform for school students to share their notes, website: https://hoa.moe. Any design would be greatly appreciated.

**Comment by PetricaT** [comment]
Sure thing, I can start working on it soon, just let me know if you want anything specific added to it.

**Comment by kowyo** [comment]
Thanks for the quick reply! We simply want a VTuber-style “HITSZ OpenAuto”. We don't have any other specific preferences or needs at the moment. We trust your creativity and expertise to come up with a design. One of member said that he would print that logo on every item he owns if someone would help us with that. So I really want to express my sincere gratitude here for your support.

**Comment by PetricaT** [comment]
Alright, 58401cf added the logo to the repo, hopefully it's up to expectations. If you need anything changed, just let me know and I can edit it.

**Comment by kowyo** [comment]
Thank you for the wonderful design! We truly appreciate this logo as it exudes cleanliness and boasts vibrant colors that breathe life into it. The incorporation of the book pattern and gears align perfectly with the backgroud of our school and website. We will feature it on our website lately, acknowledging your contribution on our 'About' page. Your work is invaluable to us, and we are immensely grateful.

**Comment by MaxwellJay256** [comment]
I really love this design. You are the best artist ever!

**Comment by longlin10086** [comment]
Thanks! We have added this logo to our website mainpage and it looks splendid!
 Here you can see it: [hoa.moe](https://hoa.moe)
Thanks again for your marvelous work!
