### ISSUE TITLE
[Logo request] Determinant

### ISSUE THREAD

**Issue by septsea** [PetricaT/ProgrammingVTuberLogos-Addon#2]
Good day.

I wrote a [book on determinants](https://github.com/septsea/det) (in Chinese, my native tongue). I made it available under a very permissive license, in order to let the book be able to be read by more people. (I also want to translate the book into other languages when I have much free time, so that even people who do not know Chinese can read it.)

I have advertised my book in many places, but the book does not seem to attract many readers. Some days ago, I learned in bilibili, a Chinese video-sharing website, that there are unofficial programming vtuber logos of some famous pieces of programming software on GitHub. These logos really caught my eyes even though I am not a programmer, so I think that it would be good to have such a logo for my project. However, I do not know how to design such a logo.

Could you please make a vtuber-styled logo that reads "Determinant"? Thank you.

**Comment by PetricaT** [comment]
Hmm, that's a interesting request. I'll see what I can do when I have the time for it, so probably in 2-3 days.

**Comment by PetricaT** [comment]
Hey! I finished your request with [b456967](https://github.com/PetricaT/ProgrammingVTuberLogos-Addon/commit/b456967a373f7404d80e87b5bed5807162eaaca5), if there is something you're not satisfied with or want changed, let me know!

**Comment by septsea** [comment]
Thank you! It looks good to me. I like it. I would like to use the logo in my project and credit you for it.

I do have something else to ask. The logo is licensed under [CC-BY-NC-SA-4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/deed.en), is it not? My book is licensed under a more permissive license than that. Do you think that my project will be a derivative of your logo if I use your logo?

**Comment by PetricaT** [comment]
I hereby grant you permission to use the logo I have created for your book however you wish, be it redistribute, modify, sell or rebrand. Use it under any license you wish, and any copies you distribute, of the logo in question, will be under your terms.

Is that good enough? :D

**Comment by septsea** [comment]
I see. Thanks so much.
